service:
  default_host: 'localhost:3000'
  
default_meta_tags:
  title: &title 'ラーメンクエスト'
  charset: 'utf-8'
  description: &description 'ラーメンクエストは、レビューやブックマーク、ランキングなどの機能を活用し、日々のラーメン巡りを記録するためのWEBサービスです。'
  keywords: 'ラーメン,口コミ,レビュー,ランキング'
  reverse: true
  og:
    title: *title
    description: *description
    type:	website
    locale: ja_JP


mail:
  activation_needed: 'ユーザー登録のご案内'
  activation_success:  'ユーザー登録完了のご案内'
  reset_password: 'パスワード再設定手続きのご案内'
  inquiry: '【Ramen Quest】お問い合わせいただきありがとうございます'
  
aws:
  s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
  secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  region: <%= ENV['AWS_REGION'] %> 
  
slack:
  webhook_url: <%= ENV['SLACK_WEBHOOK_URL'] %>
  channel: <%= ENV['SLACK_CHANNEL_NAME'] %>

gmail:
  user_name: <%= ENV['GMAIL_USER_NAME'] %>
  password: <%= ENV['GMAIL_PASSWORD'] %>